### ISSUE TITLE
autograd_lib_test.py fails

### ISSUE THREAD

**Issue by konstmish** [cybertronai/autograd-lib#1]
When I run autograd_lib_test.py I get the following output

> Traceback (most recent call last):
>   File "autograd_lib_test.py", line 239, in <module>
>     test_hessian_full()
>   File "autograd_lib_test.py", line 38, in test_hessian_full
>     dataset = u.TinyMNIST(dataset_size=batch_size, data_width=data_width)
>   File "/Users/mishchk/autograd-lib/util.py", line 237, in __init__
>     self.data = self.data[:dataset_size, :, :]
> AttributeError: 'TinyMNIST' object has no attribute 'data'

If I comment the line with "test_hessian_full()" out, then "test_hessian_diag()" fails for the same reason.

**Comment by yaroslavvb** [comment]
Should be fixed in latest version, just tried in Colab, let me know if it doesn't work

(my colab -- https://colab.research.google.com/drive/1XUjZ_OW-mHwfE4gGvMOUHLW1XXSdsT4-#scrollTo=pZR_ZZiFX7KA)
